import 'package:flutter/material.dart';
import 'package:table_calendar/table_calendar.dart';
import 'package:mob_project/screens/trips/payment_screen.dart';
import 'package:mob_project/models/models.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:mob_project/utils/modern_snackbar.dart';

class BookingScreen extends StatefulWidget {
  final String tripId;
  final TripModel trip;

  const BookingScreen({super.key, required this.tripId, required this.trip});

  @override
  State<BookingScreen> createState() => _BookingScreenState();
}

class _BookingScreenState extends State<BookingScreen> {
  DateTime _selectedDate = DateTime.now();
  DateTime _focusedDate = DateTime.now();
  int _numberOfGuests = 1;
  String _selectedTime = '06:00 AM';
  bool _isLoading = false;

  final List<String> _availableTimes = [
    '05:30 AM',
    '06:00 AM',
    '06:30 AM',
    '07:00 AM',
  ];

  double get _basePrice => widget.trip.price * _numberOfGuests;
  double get _serviceFee => _basePrice * 0.1;
  double get _taxes => _basePrice * 0.05;
  double get _finalTotal => _basePrice + _serviceFee + _taxes;

  Future<void> _handleBooking() async {
    // Validate
    if (_numberOfGuests > widget.trip.availableSeats) {
      ModernSnackBar.show(
        context,
        'Only ${widget.trip.availableSeats} seats available',
        type: SnackBarType.warning,
      );
      return;
    }

    final user = FirebaseAuth.instance.currentUser;
    if (user == null) {
      ModernSnackBar.show(
        context,
        'Please login to book a trip',
        type: SnackBarType.warning,
      );
      return;
    }

    setState(() {
      _isLoading = true;
    });

    try {
      // Create booking model
      final booking = BookingModel(
        bookingId: '', // Will be generated by Firestore
        userId: user.uid,
        tripId: widget.tripId,
        bookingDate: DateTime.now(),
        numberOfGuests: _numberOfGuests,
        selectedDate: _selectedDate,
        selectedTime: _selectedTime,
        totalPrice: _basePrice,
        serviceFee: _serviceFee,
        taxes: _taxes,
        finalTotal: _finalTotal,
        status: 'pending',
        paymentStatus: 'pending',
      );

      // Navigate to payment screen
      if (mounted) {
        Navigator.push(
          context,
          MaterialPageRoute(
            builder: (context) =>
                PaymentScreen(booking: booking, trip: widget.trip),
          ),
        );
      }
    } catch (e) {
      ModernSnackBar.show(context, 'Error: $e', type: SnackBarType.error);
    } finally {
      setState(() {
        _isLoading = false;
      });
    }
  }

  bool _isDateAvailable(DateTime date) {
    // Only allow dates in current month within next 10 days
    final now = DateTime.now();
    final today = DateTime(now.year, now.month, now.day);
    final checkDate = DateTime(date.year, date.month, date.day);
    final tenDaysLater = today.add(Duration(days: 10));
    final endOfMonth = DateTime(now.year, now.month + 1, 0);
    final maxDate = tenDaysLater.isBefore(endOfMonth)
        ? tenDaysLater
        : endOfMonth;

    return checkDate.isAfter(today) &&
        checkDate.isBefore(maxDate.add(Duration(days: 1))) &&
        checkDate.month == now.month;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Book Your Trip'),
        leading: IconButton(
          icon: const Icon(Icons.arrow_back),
          onPressed: () => Navigator.pop(context),
        ),
      ),
      body: SingleChildScrollView(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Trip Summary Card
            Container(
              margin: const EdgeInsets.all(16),
              padding: const EdgeInsets.all(16),
              decoration: BoxDecoration(
                color: Colors.lightBlue.withOpacity(0.1),
                borderRadius: BorderRadius.circular(16),
              ),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    widget.trip.title,
                    style: Theme.of(context).textTheme.titleLarge?.copyWith(
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  const SizedBox(height: 8),
                  Row(
                    children: [
                      Icon(
                        Icons.location_on,
                        size: 16,
                        color: Colors.grey[600],
                      ),
                      const SizedBox(width: 4),
                      Text(
                        widget.trip.destination,
                        style: TextStyle(color: Colors.grey[600]),
                      ),
                    ],
                  ),
                  const SizedBox(height: 8),
                  Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      Text(
                        'Available Seats: ${widget.trip.availableSeats}',
                        style: TextStyle(color: Colors.grey[700]),
                      ),
                      Text(
                        '\$${widget.trip.price.toStringAsFixed(0)} per person',
                        style: const TextStyle(
                          fontSize: 18,
                          fontWeight: FontWeight.bold,
                          color: Colors.blue,
                        ),
                      ),
                    ],
                  ),
                ],
              ),
            ),

            // Calendar Section
            Padding(
              padding: const EdgeInsets.all(16),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    'Select Date',
                    style: Theme.of(context).textTheme.titleMedium?.copyWith(
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  const SizedBox(height: 12),
                  Container(
                    decoration: BoxDecoration(
                      border: Border.all(color: Colors.grey.shade300),
                      borderRadius: BorderRadius.circular(12),
                    ),
                    child: TableCalendar(
                      firstDay: DateTime.now(),
                      lastDay: DateTime(
                        DateTime.now().year,
                        DateTime.now().month + 1,
                        0,
                      ),
                      focusedDay: _focusedDate,
                      selectedDayPredicate: (day) =>
                          isSameDay(_selectedDate, day),
                      onDaySelected: (selectedDay, focusedDay) {
                        if (_isDateAvailable(selectedDay)) {
                          setState(() {
                            _selectedDate = selectedDay;
                            _focusedDate = focusedDay;
                          });
                        }
                      },
                      enabledDayPredicate: _isDateAvailable,
                      calendarStyle: CalendarStyle(
                        selectedDecoration: const BoxDecoration(
                          color: Colors.blue,
                          shape: BoxShape.circle,
                        ),
                        todayDecoration: BoxDecoration(
                          color: Colors.blue.withOpacity(0.3),
                          shape: BoxShape.circle,
                        ),
                        disabledTextStyle: TextStyle(
                          color: Colors.grey.shade300,
                        ),
                      ),
                      headerStyle: const HeaderStyle(
                        formatButtonVisible: false,
                        titleCentered: true,
                      ),
                    ),
                  ),
                ],
              ),
            ),

            // Time Selection
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 16),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    'Select Time',
                    style: Theme.of(context).textTheme.titleMedium?.copyWith(
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  const SizedBox(height: 12),
                  Wrap(
                    spacing: 8,
                    children: _availableTimes.map((time) {
                      return ChoiceChip(
                        label: Text(time),
                        selected: _selectedTime == time,
                        onSelected: (selected) {
                          if (selected) {
                            setState(() {
                              _selectedTime = time;
                            });
                          }
                        },
                      );
                    }).toList(),
                  ),
                ],
              ),
            ),
            const SizedBox(height: 24),

            // Number of Guests
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 16),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    'Number of Guests',
                    style: Theme.of(context).textTheme.titleMedium?.copyWith(
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  const SizedBox(height: 12),
                  Container(
                    padding: const EdgeInsets.all(16),
                    decoration: BoxDecoration(
                      border: Border.all(color: Colors.grey.shade300),
                      borderRadius: BorderRadius.circular(12),
                    ),
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        const Text('Guests', style: TextStyle(fontSize: 16)),
                        Row(
                          children: [
                            IconButton(
                              icon: Icon(
                                Icons.remove_circle_outline,
                                color: _numberOfGuests > 1
                                    ? Colors.blue
                                    : Colors.grey,
                              ),
                              onPressed: _numberOfGuests > 1
                                  ? () => setState(() => _numberOfGuests--)
                                  : null,
                            ),
                            Text(
                              _numberOfGuests.toString(),
                              style: const TextStyle(
                                fontSize: 18,
                                fontWeight: FontWeight.bold,
                              ),
                            ),
                            IconButton(
                              icon: const Icon(Icons.add_circle_outline),
                              onPressed:
                                  _numberOfGuests < widget.trip.availableSeats
                                  ? () => setState(() => _numberOfGuests++)
                                  : null,
                            ),
                          ],
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            ),
            const SizedBox(height: 24),

            // Price Breakdown
            Container(
              margin: const EdgeInsets.all(16),
              padding: const EdgeInsets.all(16),
              decoration: BoxDecoration(
                color: Colors.grey.shade50,
                borderRadius: BorderRadius.circular(12),
                border: Border.all(color: Colors.grey.shade300),
              ),
              child: Column(
                children: [
                  _buildPriceRow(
                    'Base Price',
                    '\$${widget.trip.price.toStringAsFixed(0)} x $_numberOfGuests',
                    '\$${_basePrice.toStringAsFixed(2)}',
                  ),
                  const Divider(),
                  _buildPriceRow(
                    'Service Fee',
                    '10%',
                    '\$${_serviceFee.toStringAsFixed(2)}',
                  ),
                  const Divider(),
                  _buildPriceRow(
                    'Taxes',
                    '5%',
                    '\$${_taxes.toStringAsFixed(2)}',
                  ),
                  const Divider(thickness: 2),
                  _buildPriceRow(
                    'Total',
                    '',
                    '\$${_finalTotal.toStringAsFixed(2)}',
                    isTotal: true,
                  ),
                ],
              ),
            ),

            // Book Button
            Padding(
              padding: const EdgeInsets.all(16),
              child: SizedBox(
                width: double.infinity,
                child: ElevatedButton(
                  onPressed: _isLoading ? null : _handleBooking,
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Colors.blue,
                    padding: const EdgeInsets.symmetric(vertical: 16),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                  ),
                  child: _isLoading
                      ? const CircularProgressIndicator(color: Colors.white)
                      : const Text(
                          'Continue to Payment',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.bold,
                            color: Colors.white,
                          ),
                        ),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildPriceRow(
    String label,
    String detail,
    String amount, {
    bool isTotal = false,
  }) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 8),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                label,
                style: TextStyle(
                  fontSize: isTotal ? 18 : 16,
                  fontWeight: isTotal ? FontWeight.bold : FontWeight.normal,
                ),
              ),
              if (detail.isNotEmpty)
                Text(
                  detail,
                  style: TextStyle(fontSize: 12, color: Colors.grey[600]),
                ),
            ],
          ),
          Text(
            amount,
            style: TextStyle(
              fontSize: isTotal ? 20 : 16,
              fontWeight: isTotal ? FontWeight.bold : FontWeight.normal,
              color: isTotal ? Colors.blue : Colors.black,
            ),
          ),
        ],
      ),
    );
  }
}
