// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5g4hWbAbyNGLXkX4477k19Zvd98MkvgI',
    appId: '1:725074197126:web:c9460e0c3c6a12daccef07',
    messagingSenderId: '725074197126',
    projectId: 'skyfly-edbac',
    authDomain: 'skyfly-edbac.firebaseapp.com',
    storageBucket: 'skyfly-edbac.firebasestorage.app',
    measurementId: 'G-289RB8MFKJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2T-_WTktL6fL5MWyWNcd9fbAmpd4cEhA',
    appId: '1:725074197126:android:17f33c3c6ff8d450ccef07',
    messagingSenderId: '725074197126',
    projectId: 'skyfly-edbac',
    storageBucket: 'skyfly-edbac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeK96bhPNTLaQOmLtdlRYA8yiDZXij-O0',
    appId: '1:725074197126:ios:7564db504bcc97e5ccef07',
    messagingSenderId: '725074197126',
    projectId: 'skyfly-edbac',
    storageBucket: 'skyfly-edbac.firebasestorage.app',
    iosClientId: '725074197126-pi39c3mboq7ptfnqapsjn8uag6gs4cha.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeK96bhPNTLaQOmLtdlRYA8yiDZXij-O0',
    appId: '1:725074197126:ios:7564db504bcc97e5ccef07',
    messagingSenderId: '725074197126',
    projectId: 'skyfly-edbac',
    storageBucket: 'skyfly-edbac.firebasestorage.app',
    iosClientId: '725074197126-pi39c3mboq7ptfnqapsjn8uag6gs4cha.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5g4hWbAbyNGLXkX4477k19Zvd98MkvgI',
    appId: '1:725074197126:web:9dbc7f3b4065d92dccef07',
    messagingSenderId: '725074197126',
    projectId: 'skyfly-edbac',
    authDomain: 'skyfly-edbac.firebaseapp.com',
    storageBucket: 'skyfly-edbac.firebasestorage.app',
    measurementId: 'G-DBHMM9JZQS',
  );
}
