// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCrT35mqHTARj2fm2o4UmfZtVet6M-2bo',
    appId: '1:391308780574:web:8598182f69df2b63a4ba0f',
    messagingSenderId: '391308780574',
    projectId: 'newskyfly-e5731',
    authDomain: 'newskyfly-e5731.firebaseapp.com',
    storageBucket: 'newskyfly-e5731.firebasestorage.app',
    measurementId: 'G-K4FL00H5Z1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADgkhI3J83NEw3ZCse0FpJvkLJGIkXtmg',
    appId: '1:391308780574:android:e7e2cf0af67b955ea4ba0f',
    messagingSenderId: '391308780574',
    projectId: 'newskyfly-e5731',
    storageBucket: 'newskyfly-e5731.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1n4RODkxT7nolKg0BO6TdCBYnKWpYTVQ',
    appId: '1:391308780574:ios:d56a1e614bfc6b89a4ba0f',
    messagingSenderId: '391308780574',
    projectId: 'newskyfly-e5731',
    storageBucket: 'newskyfly-e5731.firebasestorage.app',
    iosBundleId: 'com.example.mobProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1n4RODkxT7nolKg0BO6TdCBYnKWpYTVQ',
    appId: '1:391308780574:ios:d56a1e614bfc6b89a4ba0f',
    messagingSenderId: '391308780574',
    projectId: 'newskyfly-e5731',
    storageBucket: 'newskyfly-e5731.firebasestorage.app',
    iosBundleId: 'com.example.mobProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCrT35mqHTARj2fm2o4UmfZtVet6M-2bo',
    appId: '1:391308780574:web:862126fb98ac12daa4ba0f',
    messagingSenderId: '391308780574',
    projectId: 'newskyfly-e5731',
    authDomain: 'newskyfly-e5731.firebaseapp.com',
    storageBucket: 'newskyfly-e5731.firebasestorage.app',
    measurementId: 'G-5PCTC2K8L8',
  );

}